
train:
  max_fea_length: 1000
  max_seq_length: 200
  threshold: 1
  num_workers: 2
  batch_size: 1
  max_epochs: 200
  d_model: 512
  d_ff: 512
  d_vf: 768
  num_heads: 8
  num_layers: 6
  dropout: 0.1
  logit_layers: 1
  bos_idx: 0
  eos_idx: 0
  pad_idx: 0
  use_bn: 0
  drop_prob_lm: 0.5
  sample_method: beam_search
  beam_size: 10
  temperature: 1.5
  sample_n: 1
  group_size: 5
  output_logsoftmax: 1
  decoding_constraint: 1
  suppress_UNK: 1
  block_trigrams: 1
  lr: 0.00005
  d1: 768
  d2: 768
  embeddings_path: /mnt/saarthak/datasets/REG_processed/20x_512px_0px_overlap/slide_features_titan
  embeddings_path_2: /mnt/saarthak/datasets/REG_processed/20x_512px_0px_overlap/features_conch_v15
  reports_json_path: /mnt/surya/train.json
  ckpt_path: /mnt/surya/projects/Wsi-rgen/checkpoints/5
  model_save_path: /mnt/surya/projects/Wsi-rgen/saved_models/mi_gen_titan_plus_conch1.5_20250804_1_model.ckpt
  results_path: /mnt/surya/projects/Wsi-rgen/results
  devices: 1,2,3,4,6
  fast_dev_run: false
  num_folds: 3

