train:
  max_fea_length: 2000
  max_seq_length: 512
  threshold: 1
  num_workers: 2
  batch_size: 1
  max_epochs: 200
  d_model: 768
  d_ff: 768
  d_vf: 768
  num_heads: 4
  num_layers: 3
  dropout: 0.4
  dropout_mlp: 0.4
  weight_decay: 0.01
  logit_layers: 3
  bos_idx: 0
  eos_idx: 0
  pad_idx: 0
  use_bn: 0
  drop_prob_lm: 0.4
  sample_method: greedy
  concept_lambda: 0.7
  diversity_lambda: 0.7
  length_penalty: wu_0.7
  beam_size: 6
  temperature: 0.8
  sample_n: 2
  group_size: 3
  output_logsoftmax: 1
  decoding_constraint: 1
  suppress_UNK: 1
  block_trigrams: 1
  lr: 0.0001
  lr_patience: 2
  d1: 768
  d2: 768
  gd: 512
  gcd: 49
  embeddings_path: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/brca/slide_features_titan
  embeddings_path_2: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/brca/features_conch_v15
  gecko_emb_path: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/brca/gecko/features
  reports_json_path: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/brca/tcga_brca_reports.json
  ckpt_path: /lustre/nvwulf/scratch/sbsingh/tcga_brca/experiments
  model_load_path: /lustre/nvwulf/home/sbsingh/inference/tcga_brca/202040/model_epoch=66_val_loss=1.17256_val_reg=0.00000.ckpt
  results_path: /lustre/nvwulf/home/sbsingh/tcga_brca_results_new
  predict_embeddings_path_1: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/brca/slide_features_titan
  predict_embeddings_path_2: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/brca/features_conch_v15
  gecko_predict_emb_path: /lustre/nvwulf/projects/PrasannaGroup-nvwulf/surya/datasets/TCGA_processed/brca/gecko/features
  devices: 4
  fast_dev_run: false
  num_folds: 3
  resume: false
